_wandb:
    value:
        cli_version: 0.26.1
        code_path: code/gpt2_gpipe_memory_profile.py
        e:
            mg6bc92yz0ql3ksmsuq5h30qrvst9huf:
                codePath: gpt2_gpipe_memory_profile.py
                codePathLocal: gpt2_gpipe_memory_profile.py
                email: r13922a13@ntu.edu.tw
                executable: /home/r13922a13/anaconda3/envs/gpt2_gpipe_mem/bin/python
                git:
                    commit: 0b2d56f97a94585d47e4c35a04dda9187b4e72c2
                    remote: git@github.com:a0kuma/mew_mem_1.git
                host: puipui
                os: Linux-6.8.0-1035-oracle-x86_64-with-glibc2.35
                program: /home/r13922a13/mew_mem_1/gpt2_gpipe_memory_profile.py
                python: CPython 3.10.19
                root: /home/r13922a13/mew_mem_1
                startedAt: "2026-05-12T19:04:21.587404Z"
                writerId: mg6bc92yz0ql3ksmsuq5h30qrvst9huf
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 11
                - 49
            "2":
                - 1
                - 11
                - 49
            "3":
                - 2
            "4": 3.10.19
            "5": 0.26.1
            "6": 5.2.0
            "12": 0.26.1
            "13": linux-x86_64
